# Generated by Django 2.0.4 on 2018-05-14 07:12

from django.db import migrations


def add_site_data(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    new_domain = 'site.django-unleashed.com'
    new_name = 'Startup Organizer'
    site_id = getattr(settings, 'SITE_ID', 1)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
    ]
