# Generated by Django 2.0.4 on 2018-05-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('organizer', '0004_startup_data')
    ]

    operations = [
    ]
