# Generated by Django 2.0.4 on 2018-05-12 02:04

from django.db import migrations

TAGS = (
    'augmented reality', 'augmented-reality'
    )

def add_tag_data(apps, schema_editor):
    Tag = apps.get_model('orgainzer', 'Tag')
    for tag_name, tag_slug in TAGS:
        Tag.objects.create(name=tag_name, slug=tag_slug)


def remove_tag_data(apps, schema_editor):
    Tag = apps.get_model('organizer', 'Tag')
    for _, tag_slug in TAGS:
        Tag.objects.get(slug=tag_slug).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20180512_0153'),
    ]

    operations = [
        migrations.RunPython(add_tag_data, remove_tag_data)
    ]
