# Generated by Django 2.0.4 on 2018-05-12 04:49

from django.db import migrations

TAGS = (
    ('augmented reality', 'augmented-reality'),
)


def add_tag_data(apps, scheme_editor):
    Tag = apps.get_model('organizer', 'Tag')
    for tag_name, slug_name in TAGS:
        Tag.objects.create(name=tag_name, slug=slug_name)


def remove_tag_data(apps, scheme_editor):
    Tag = apps.get_model('organizer', 'Tag')
    for _, slug_name in TAGS:
        Tag.objects.get(slug__iexact=slug_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20180512_0442'),
    ]

    operations = [
        migrations.RunPython(add_tag_data, remove_tag_data)
    ]
