# Generated by Django 2.0.4 on 2018-05-12 08:46

from django.db import migrations

TAGS = (('augmented reality', 'augmented-reality'),
        )


def add_tag_data(apps, schema):
    Tag = apps.get_model('organizer', 'Tag')
    for tag_name, tag_slug in TAGS:
        Tag.objects.create(name=tag_name, slug=tag_slug)

def remove_tag_data(apps, schema):
    Tag = apps.get_model('organizer', 'Tag')
    for _, tag_slug in TAGS:
        Tag.objects.get(slug=tag_slug).delete()
class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20180512_0843'),
    ]

    operations = [
        migrations.RunPython(add_tag_data, remove_tag_data)
    ]
