# Generated by Django 2.0.4 on 2018-05-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20180512_0204'),
    ]

    operations = [
    ]
