# Generated by Django 2.0.4 on 2018-05-12 09:21

from django.db import migrations
from datetime import date
STARTUPS = [
    {
        "name": "Arachnobots",
        "slug": "arachnobots",
        "contact": "contact@arachnobots.com",
        "description":
        "Remote-controlled internet-enabled "
        "Spider Robots.",
        "founded_date": date(2014, 10, 31),
        "tags": ["mobile", "augmented-reality"],
        "website":
        "http://frightenyourroommate.com/",
    },
]


def add_startup_data(apps, schema):
    Startup = apps.get_model('organizer', 'Startup')
    for startup in STARTUPS:
        startup_object = Startup.objects.create(
            name=startup['name'],
            slug=startup['slug'],
            contact=startup['contact'],
            description=startup['description'],
            founded_date=startup['founded_date'],
            website=startup['website'])
    for tag_slug in startup['tags']:
        startup_object.tags.add(Tag.objects.get(slug=tag_slug))


def remove_startup_data(apps, schema_editor):
    Startup = apps.get_model(
        'organizer', 'Startup')
    for startup in STARTUPS:
        startup_object = Startup.objects.get(
            slug=startup['slug'])
        startup_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_tag_data'),
    ]

    operations = [
    ]
